import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Clock, Hash, X, CheckCircle, AlertCircle, Circle, MapPin } from 'lucide-react';
import type { Token } from '../../types';
import { formatRelative, formatDate, formatTime, priorityBadgeClass } from '../../utils';

interface HistoryProps {
  tokens: Token[];
  isDark: boolean;
}

export default function HistoricalIntelligence({ tokens, isDark }: HistoryProps) {
  const [selected, setSelected] = useState<Token | null>(null);
  const [filter, setFilter] = useState<'all' | 'active' | 'resolved' | 'pending'>('all');

  const filtered = tokens.filter(t => filter === 'all' || t.status === filter);

  const StatusIcon = ({ status }: { status: string }) => {
    if (status === 'active') return <AlertCircle className="w-3.5 h-3.5 text-red-400" />;
    if (status === 'resolved') return <CheckCircle className="w-3.5 h-3.5 text-green-400" />;
    return <Circle className="w-3.5 h-3.5 text-yellow-400" />;
  };

  return (
    <div className="h-full overflow-y-auto p-4 space-y-4 relative">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h1 className="text-lg font-bold text-white">Historical Intelligence</h1>
          <p className="text-xs text-gray-500 font-sans mt-0.5">{tokens.length} total tokens in ledger</p>
        </div>
        <div className="flex gap-1">
          {(['all', 'active', 'resolved', 'pending'] as const).map(f => (
            <button key={f} onClick={() => setFilter(f)}
              className={`px-3 py-1.5 rounded-lg text-xs font-sans uppercase tracking-wider transition-all ${
                filter === f ? 'bg-orange-500/20 text-orange-400 border border-orange-500/30' : 'border border-white/[0.08] text-gray-500 hover:text-white'
              }`}>
              {f}
            </button>
          ))}
        </div>
      </div>

      {/* Timeline */}
      <div className="space-y-2">
        {filtered.map((token, i) => (
          <motion.div key={token.id}
            initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: i * 0.04 }}
            onClick={() => setSelected(token)}
            className="bg-[#0F1117] border border-white/[0.06] rounded-xl p-4 cursor-pointer hover:border-orange-500/20 transition-all group">
            <div className="flex items-start gap-4">
              <div className="flex flex-col items-center gap-1 shrink-0">
                <div className="w-8 h-8 rounded-lg bg-white/[0.04] border border-white/[0.08] flex items-center justify-center">
                  <Hash className="w-4 h-4 text-orange-400" />
                </div>
                {i < filtered.length - 1 && <div className="w-px h-4 bg-white/[0.06]" />}
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 flex-wrap mb-1.5">
                  <span className="font-mono text-sm font-bold text-orange-400">{token.id}</span>
                  <span className={`text-xs font-mono px-2 py-0.5 rounded border ${priorityBadgeClass(token.priority)}`}>
                    {token.priority.toUpperCase()}
                  </span>
                  <div className="flex items-center gap-1">
                    <StatusIcon status={token.status} />
                    <span className={`text-xs font-mono ${
                      token.status === 'active' ? 'text-red-400' : token.status === 'resolved' ? 'text-green-400' : 'text-yellow-400'
                    }`}>{token.status.toUpperCase()}</span>
                  </div>
                  <span className="ml-auto text-xs font-mono text-gray-500 flex items-center gap-1">
                    <Clock className="w-3.5 h-3.5" />{formatRelative(token.timestamp)}
                  </span>
                </div>
                <div className="text-xs font-semibold text-white mb-0.5">{token.type} · {token.location}</div>
                <div className="text-xs text-gray-400 truncate">{token.description}</div>
                <div className="flex items-center gap-3 text-[11px] font-mono text-gray-500 flex-wrap mt-1">
                  {token.lat && token.lng && (
                    <span className="text-cyan-400 flex items-center gap-1">
                      <MapPin className="w-3 h-3 text-cyan-400" />
                      {token.lat.toFixed(4)}°N, {token.lng.toFixed(4)}°E
                    </span>
                  )}
                  <span>Generated by: <span className="font-mono">{token.generatedBy}</span></span>
                </div>
              </div>
              <div className="text-xs text-gray-500 group-hover:text-orange-400 transition-colors font-mono shrink-0">VIEW →</div>
            </div>
          </motion.div>
        ))}
      </div>

      {/* Token detail modal */}
      <AnimatePresence>
        {selected && (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
            className="fixed inset-0 z-[2000] flex items-center justify-center p-4"
            style={{ background: 'rgba(0,0,0,0.8)', backdropFilter: 'blur(8px)' }}
            onClick={e => { if (e.target === e.currentTarget) setSelected(null); }}>
            <motion.div initial={{ scale: 0.9, y: 20 }} animate={{ scale: 1, y: 0 }} exit={{ scale: 0.9, y: 20 }}
              className="w-full max-w-lg rounded-2xl border border-white/[0.08] overflow-hidden bg-[#0F1117]">
              <div className="h-px bg-gradient-to-r from-transparent via-orange-500 to-transparent" />
              <div className="p-6">
                <div className="flex items-center justify-between mb-6">
                  <div>
                    <div className="font-mono text-xl font-bold text-orange-400">{selected.id}</div>
                    <div className="text-xs text-gray-500 font-sans mt-0.5">Intelligence Token · Ledger Entry</div>
                  </div>
                  <button onClick={() => setSelected(null)} className="text-gray-500 hover:text-white transition-colors">
                    <X className="w-5 h-5" />
                  </button>
                </div>

                <div className="space-y-3">
                  {[
                    { label: 'Type', value: selected.type },
                    { label: 'Location', value: selected.location },
                    { label: 'Priority', value: selected.priority.toUpperCase() },
                    { label: 'Status', value: selected.status.toUpperCase() },
                    { label: 'Date', value: formatDate(selected.timestamp) },
                    { label: 'Time', value: formatTime(selected.timestamp) },
                    { label: 'Generated By', value: selected.generatedBy },
                  ].map(({ label, value }) => (
                    <div key={label} className="flex justify-between py-2 border-b border-white/[0.04]">
                      <span className="text-xs font-sans text-gray-500 uppercase tracking-wider">{label}</span>
                      <span className="text-xs font-mono text-white">{value}</span>
                    </div>
                  ))}
                  <div className="py-2">
                    <div className="text-xs font-sans text-gray-500 uppercase tracking-wider mb-2">Description</div>
                    <p className="text-xs text-gray-300 leading-relaxed font-sans">{selected.description}</p>
                  </div>

                  {/* Dynamic dark-mode static map representation */}
                  {selected.mapImage ? (
                    <div className="mt-4 rounded-xl overflow-hidden border border-white/[0.08] bg-black/40 relative">
                      <div className="text-[10px] font-mono text-gray-400 bg-black/70 px-2 py-1 absolute top-2 left-2 rounded z-10 border border-white/[0.05]">
                        📍 COORDINATES: {selected.lat?.toFixed(5)}°N, {selected.lng?.toFixed(5)}°E
                      </div>
                      <img
                        src={selected.mapImage}
                        alt="Location Map"
                        className="w-full h-[200px] object-cover"
                        style={{
                          filter: isDark ? 'invert(0.9) hue-rotate(180deg) brightness(0.7) contrast(1.3) saturate(0.8)' : 'none',
                        }}
                      />
                    </div>
                  ) : selected.lat && selected.lng ? (
                    <div className="mt-4 rounded-xl overflow-hidden border border-white/[0.08] bg-black/40 relative">
                      <div className="text-[10px] font-mono text-gray-400 bg-black/70 px-2 py-1 absolute top-2 left-2 rounded z-10 border border-white/[0.05]">
                        📍 COORDINATES: {selected.lat?.toFixed(5)}°N, {selected.lng?.toFixed(5)}°E
                      </div>
                      <img
                        src={`https://static-maps.yandex.ru/1.x/?ll=${selected.lng},${selected.lat}&z=15&l=map&size=450,200&pt=${selected.lng},${selected.lat},pm2orl`}
                        alt="Location Map"
                        className="w-full h-[200px] object-cover"
                        style={{
                          filter: isDark ? 'invert(0.9) hue-rotate(180deg) brightness(0.7) contrast(1.3) saturate(0.8)' : 'none',
                        }}
                      />
                    </div>
                  ) : null}
                </div>

                <div className="flex gap-2 mt-6">
                  <button className="flex-1 py-2 rounded-lg border border-green-500/30 text-green-400 text-xs font-mono hover:bg-green-500/10 transition-all">
                    Mark Resolved
                  </button>
                  <button className="flex-1 py-2 rounded-lg border border-white/[0.08] text-gray-400 text-xs font-mono hover:text-white transition-all">
                    Export Token
                  </button>
                </div>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
